name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pipenv
        run: |
           python -m pip install --upgrade pip
           pip install pipenv
           
      #- name: Install bib2md dependencies
      #  run: |
      #     pipenv install
           
      #- name: Generate publications
      #  run: |
      #    make publication
          
      - name: checkout latest code
        uses: actions/checkout@v2
        
      - name: build jekyll site
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
